### ISSUE TITLE
量化MobileNetV2_224报错

### ISSUE THREAD

**Issue by xutch** [alibaba/MNN#1001]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
x86_64  Ubuntu 18.04.4

# Github版本: 
# Github Version:

Master commit_id: ff86425edca55d0690e21ec1eb86a685da103fbc (Thu Jul 23 16:54:55 2020)

# 编译方式:  
# Compiling Method

```
cmake .. -DMNN_BUILD_CONVERTER=true -DMNN_BUILD_QUANTOOLS=on && make -j8
```

# 编译日志:
# Build Log:

```
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
--      System: Linux
--      Processor: x86_64
--      Metal: OFF
--      OpenCL: OFF
--      OpenGL: OFF
--      Vulkan: OFF
--      ARM82: OFF
--      OpenMP: OFF
--      Hidden: TRUE
--      Build Path: /data/env/Euler_compile_env/home/MNN/build
-- x86_64: Open SSE
-- Onnx: /data/env/Euler_compile_env/home/MNN/build/tools/converter/onnx.pb.h;/data/env/Euler_compile_env/home/MNN/build/tools/converter/onnx-operators.pb.h
-- Configuring done
-- Generating done
-- Build files have been written to: /data/env/Euler_compile_env/home/MNN/build
[  1%] Built target MNNSSE
[  1%] Built target MNNAVX
[  2%] Built target MNNCV
[  2%] Built target GenVCSHDR
[  5%] Built target MNNCore
[  9%] Built target MNNCompute
[ 22%] Built target MNNShape
[ 23%] Built target MNNMath
[ 23%] Built target MNNConverterMNN
[ 30%] Built target MNNConverterONNX
[ 49%] Built target MNNCPU
[ 56%] Built target MNNConverterCaffe
[ 56%] Built target MNNDump2Json
[ 57%] Built target OnnxClip
[ 63%] Built target MNNConverterTFL
[ 63%] Built target MNNX8664
[ 78%] Built target MNNConverterTF
[ 91%] Built target MNNConverterOpt
[ 91%] Built target MNN
[ 93%] Built target MNN_Express
[ 93%] Built target testModel.out
[ 94%] Built target MNNV2Basic.out
[ 94%] Built target getPerformance.out
[ 94%] Built target checkInvalidValue.out
[ 95%] Built target quantized.out
[ 96%] Built target testModelWithDescrisbe.out
[ 97%] Built target mobilenetTest.out
[ 98%] Built target timeProfile.out
[ 99%] Built target backendTest.out
[ 99%] Built target MNNConvertDeps
[ 99%] Built target TestConvertResult
[100%] Built target MNNConvert
```

1. 模型转换成功

```
./MNNConvert -f TFLITE --modelFile mobilenet_v2_1.0_224.tflite --MNNModel mobilenet_v2.mnn --bizCode biz

```
2. 量化模型失败

```
./quantized.out mobilenet_v2.mnn mobilenet_v2_quant.mnn config.json
```
```
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/quantized.cpp:21: >>> modelFile: mobilenet_v2.mnn
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/quantized.cpp:22: >>> preTreatConfig: config.json
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/quantized.cpp:23: >>> dstFile: mobilenet_v2_quant.mnn
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/quantized.cpp:50: Calibrate the feature and quantize model...
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/calibration.cpp:109: Use feature quantization method: KL
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/calibration.cpp:110: Use weight quantization method: MAX_ABS
[17:35:27] /data/env/Euler_compile_env/home/MNN/tools/quantization/Helper.cpp:100: used image num: 50
Illegal instruction (core dumped)
```

GDB的结果：

```

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[16:59:47] /home/MNN/tools/quantization/quantized.cpp:21: >>> modelFile: mobilenet_v2.mnn
[16:59:47] /home/MNN/tools/quantization/quantized.cpp:22: >>> preTreatConfig: config.json
[16:59:47] /home/MNN/tools/quantization/quantized.cpp:23: >>> dstFile: mobilenet_v2_quant.mnn
[16:59:47] /home/MNN/tools/quantization/quantized.cpp:50: Calibrate the feature and quantize model...
[16:59:47] /home/MNN/tools/quantization/calibration.cpp:109: Use feature quantization method: KL
[16:59:47] /home/MNN/tools/quantization/calibration.cpp:110: Use weight quantization method: MAX_ABS
[16:59:47] /home/MNN/tools/quantization/Helper.cpp:100: used image num: 50
[New Thread 0x7ffff5aa7700 (LWP 33510)]
[New Thread 0x7ffff52a6700 (LWP 33511)]
[New Thread 0x7ffff4aa5700 (LWP 33512)]

Thread 3 "quantized.out" received signal SIGILL, Illegal instruction.
[Switching to Thread 0x7ffff52a6700 (LWP 33511)]
0x00007ffff799f94c in _SSE_MNNPackedMatMul(float*, float const*, float const*, unsigned long const*, float*, float const*, float const*) ()
   from /home/MNN/build/libMNN.so
(gdb) bt
#0  0x00007ffff799f94c in _SSE_MNNPackedMatMul(float*, float const*, float const*, unsigned long const*, float*, float const*, float const*) ()
   from /home/MNN/build/libMNN.so
#1  0x00007ffff78f3859 in std::_Function_handler<void (int), MNN::ConvolutionTiledExecutorBasic::onResize(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
   from /home/MNN/build/libMNN.so
#2  0x00007ffff78f3899 in std::_Function_handler<void (int), MNN::ConvolutionTiledExecutorBasic::onExecute(std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&, std::vector<MNN::Tensor*, std::allocator<MNN::Tensor*> > const&)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
   from /home/MNN/build/libMNN.so
#3  0x00007ffff7998c3b in std::thread::_State_impl<std::thread::_Invoker<std::tuple<MNN::ThreadPool::ThreadPool(int)::{lambda()#1}> > >::_M_run() ()
   from /home/MNN/build/libMNN.so
#4  0x00007ffff75a36df in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff693b6db in start_thread (arg=0x7ffff52a6700) at pthread_create.c:463
#6  0x00007ffff6e7888f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by jxt1234** [comment]
你的电脑环境是?

**Comment by wujiexiaowugui** [comment]
我也遇到了这个问题，电脑环境是Ubuntu16.04 x64
