### ISSUE TITLE
MNN.expr.matmul 与 torch.matmul的计算行为不一致

### ISSUE THREAD

**Issue by meteorlin** [alibaba/MNN#1449]
我希望在MNN中部署该[动态知识图谱嵌入方法](https://github.com/lienwc/DKGE/)，目前代码写得差不多但遇到几个问题：
1. `MNN.expr.matmul(a, b)`中，如果b仅有一行就总是会报`RuntimeError: unable to get variable info`的错误，而相同的计算在Pytorch中是可行的，如：
```python
# Pytorch下可行
>>> c
tensor([[ 0.,  8.],
        [-5.,  0.]])
>>> d
tensor([2., 3.])
>>> torch.matmul(d, c)
tensor([-15.,  16.])

# MNN下不可行
>>> c
array([[ 0.,  8.],
       [-5.,  0.]], dtype=float32)
>>> d
array([2., 3.], dtype=float32)
>>> F.matmul(c, d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Library\Python-Library\MNN\lib\site-packages\MNN\__init__.py", line 141, in _
read
    return self.read().__repr__()
RuntimeError: unable to get variable info
```
2. 在优化器进行优化的过程中，如果某个原来设定的参数A在`forward`的过程中参与了`MNN.expr.matmul`操作，那么其维度会转换为另一个参与乘法的参数的维度，例如下面代码中的`entity_gcn_weight`和`v_ent`，在经过`train_func`的`opt.step(loss)`后分别从原来的`[100, 100]`、`[100, 1]`变成`[500, 100, 100]`、`[500, 100, 1]`。由于目前采用的是随机数据，我也不太确定这个维度转换对模型是否有影响，但总觉得不对劲。
```python
import copy
import math
import time

import MNN
import numpy as np
import MNN.nn as nn
import MNN.expr as F

dtype = F.dtype

batch_size_ = 500
dim = 100
max_context_num = 30


class DynamicDKGE(nn.Module):
    def __init__(self):
        super(DynamicDKGE, self).__init__()

        # gcn权重
        size = dim * dim
        stdv = 1. / math.sqrt(size)
        self.entity_gcn_weight = F.const(np.random.uniform(low=-stdv, high=stdv, size=size).flatten().tolist(),
                                         [dim, dim], dtype=dtype.float)
        self.relation_gcn_weight = F.const(np.random.uniform(low=-stdv, high=stdv, size=size).flatten().tolist(),
                                           [dim, dim], dtype=dtype.float)
        # 门控权重
        self.gate_entity = F.const(np.random.uniform(size=[dim, 1]).flatten().tolist(), [dim, 1], dtype=dtype.float)
        self.gate_relation = F.const(np.random.uniform(size=[dim, 1]).flatten().tolist(), [dim, 1], dtype=dtype.float)
        # 注意力机制，每一行代表每一维的权重（一个列向量）
        self.v_ent = F.const(np.random.uniform(size=[dim, 1]).flatten().tolist(), [dim, 1], dtype=dtype.float)
        self.v_rel = F.const(np.random.uniform(size=[dim, 1]).flatten().tolist(), [dim, 1], dtype=dtype.float)

        # 转换为可训练参数
        # gcn权重
        self.entity_gcn_weight.fix_as_trainable()
        self.relation_gcn_weight.fix_as_trainable()
        # 门控权重
        self.gate_entity.fix_as_trainable()
        self.gate_relation.fix_as_trainable()
        # 注意力机制，每一行代表每一维的权重
        self.v_ent.fix_as_trainable()
        self.v_rel.fix_as_trainable()

    def gcn(self, a, h, entity_type: bool = True):
        """
        GCN
        :param a:
        :param h:
        :param entity_type: True代表更新实体的权重，反之为更新关系的权重
        :return:
        """
        return F.relu(F.matmul(F.matmul(a, h), self.entity_gcn_weight if entity_type else self.relation_gcn_weight))

    # 计算注意力机制的权重
    def score(self, o, adj_vec_list, entity_type: bool = True):
        x = F.concat(tuple([o] * (max_context_num + 1)), axis=1)
        os = F.reshape(x, [x.shape[0], max_context_num + 1, dim])
        temp = F.relu(F.multiply(adj_vec_list, os))
        # 此处，self.v_ent必须为[dim, 1]，不能是[dim]，否则无法进行矩阵乘法，输出为[500, max_context_num + 1, 1]
        # 通过F.squeeze将最后的1去掉（即将最下层的1上升一层）
        return F.squeeze(F.matmul(temp, self.v_ent if entity_type else self.v_rel), [2])

    def calc_sub_graph_vec(self, o, adj_vec_list, entity_type: bool = True):
        alpha = self.score(o, adj_vec_list, entity_type)
        alpha = F.softmax(alpha)
        # 通过F.unsqueeze将第二维全部下降一维
        return F.reduce_sum(F.multiply(F.unsqueeze(alpha, [2]), adj_vec_list), [1])

    def cal_final_context_embedding(self, original_embedding, sub_graph_vec, entity_type: bool = True):
        sig = F.squeeze(F.sigmoid(self.gate_entity if entity_type else self.gate_relation), [1])
        return F.multiply(sig, original_embedding) + F.multiply(1 - sig, sub_graph_vec)

    @staticmethod
    def cal_final_score_test(h, t, r):
        # 矩阵的每一行各计算一个F范数
        # Frobenius 范数的定义: https://www.zhihu.com/question/22475774/answer/21479817
        return F.sqrt(F.reduce_sum(F.square(h + t - r), axis=[1]))

    def forward(self, train_data: list):
        ph_A = train_data[0]
        pr_A = train_data[1]
        pt_A = train_data[2]
        ph_adj_entity_vec_list = train_data[3]
        pr_adj_entity_vec_list = train_data[4]
        pt_adj_entity_vec_list = train_data[5]
        p_h = train_data[6]
        p_r = train_data[7]
        p_t = train_data[8]
        nh_A = train_data[9]
        nr_A = train_data[10]
        nt_A = train_data[11]
        nh_adj_entity_vec_list = train_data[12]
        nr_adj_entity_vec_list = train_data[13]
        nt_adj_entity_vec_list = train_data[14]
        n_h = train_data[15]
        n_r = train_data[16]
        n_t = train_data[17]

        ph_o = self.cal_final_context_embedding(p_h, self.calc_sub_graph_vec(p_h, self.gcn(ph_A,
                                                                                           ph_adj_entity_vec_list)))
        pr_o = self.cal_final_context_embedding(p_r, self.calc_sub_graph_vec(p_r, self.gcn(pr_A,
                                                                                           pr_adj_entity_vec_list)))
        pt_o = self.cal_final_context_embedding(p_t, self.calc_sub_graph_vec(p_t, self.gcn(pt_A,
                                                                                           pt_adj_entity_vec_list)))

        nh_o = self.cal_final_context_embedding(n_h, self.calc_sub_graph_vec(n_h, self.gcn(nh_A,
                                                                                           nh_adj_entity_vec_list)))
        nr_o = self.cal_final_context_embedding(n_r, self.calc_sub_graph_vec(n_r, self.gcn(nr_A,
                                                                                           nr_adj_entity_vec_list)))
        nt_o = self.cal_final_context_embedding(n_t, self.calc_sub_graph_vec(n_t, self.gcn(nt_A,
                                                                                           nt_adj_entity_vec_list)))

        p_score = model.cal_final_score_test(ph_o, pt_o, pr_o)
        n_score = model.cal_final_score_test(nh_o, nt_o, nr_o)

        return p_score, n_score


def train_func(net, opt):
    """train function"""
    net.train(True)

    t0 = time.time()
    _train_data = [
        F.const(np.random.random(dim1).flatten().tolist(), dim1),
        F.const(np.random.random(dim1).flatten().tolist(), dim1),
        F.const(np.random.random(dim1).flatten().tolist(), dim1),

        F.const(np.random.random(dim3).flatten().tolist(), dim3),
        F.const(np.random.random(dim3).flatten().tolist(), dim3),
        F.const(np.random.random(dim3).flatten().tolist(), dim3),

        F.const(np.random.random(dim2).flatten().tolist(), dim2),
        F.const(np.random.random(dim2).flatten().tolist(), dim2),
        F.const(np.random.random(dim2).flatten().tolist(), dim2),

        F.const(np.random.random(dim1).flatten().tolist(), dim1),
        F.const(np.random.random(dim1).flatten().tolist(), dim1),
        F.const(np.random.random(dim1).flatten().tolist(), dim1),

        F.const(np.random.random(dim3).flatten().tolist(), dim3),
        F.const(np.random.random(dim3).flatten().tolist(), dim3),
        F.const(np.random.random(dim3).flatten().tolist(), dim3),

        F.const(np.random.random(dim2).flatten().tolist(), dim2),
        F.const(np.random.random(dim2).flatten().tolist(), dim2),
        F.const(np.random.random(dim2).flatten().tolist(), dim2),
    ]

    for i in range(3):
        x1 = copy.deepcopy(net.parameters[0].read()[0][0])

        p_score, n_score = net.forward(_train_data)
        loss = margin_ranking_loss(p_score, n_score, False, 10)
        opt.step(loss)
        print("train loss: ", loss.read())

        y1 = net.parameters[0].read()[0][0]
        print(x1 == y1)

    t1 = time.time()
    cost = t1 - t0
    print("Epoch cost: %.3f s." % cost)
    F.save(net.parameters, "temp.mnist.snapshot")


def margin_ranking_loss(v1, v2, first_higher_second, margin=10):
    """
    对应Pytorch的 nn.MarginRankingLoss
    参考：https://pytorch.org/docs/stable/generated/torch.nn.MarginRankingLoss.html
    :param v1:
    :param v2:
    :param first_higher_second:
    :param margin:
    :return:
    """
    flag = -1 if first_higher_second else 1
    zero = F.const(np.zeros([1]).flatten().tolist(), [1])
    result = F.reduce_sum(v1 - v2, axis=[0]) * flag + margin
    return F.maximum(zero, result)


def learning_rate_scheduler(lr, epoch):
    if (epoch + 1) % 2 == 0:
        lr *= 0.1
    return lr


if __name__ == '__main__':
    model = DynamicDKGE()

    dim1 = [batch_size_, max_context_num + 1, max_context_num + 1]
    dim2 = [batch_size_, dim]
    dim3 = [batch_size_, max_context_num + 1, dim]

    opt = MNN.optim.SGD(model, 0.01, 0.9, 0.0005)

    for epoch in range(0, 10):
        opt.learning_rate = learning_rate_scheduler(opt.learning_rate, epoch)
        train_func(model, opt)
        model.train(False)
```

目前，对于第一个问题，我的解决方法是将第二个参与乘法计算的Var的维度一开始定义为列向量，然后在matmul后通过`F.squeeze`恢复正确的维度。参见：DynamicDKGE.score；
所以想请教各位，这俩问题有什么好的解决方案吗？
提前致谢！

**Comment by yyfcc17** [comment]
F.matmul(d, c)，你写成F.matmul(c, d)了

**Comment by wangzhaode** [comment]
expr.matmul并不会跟torch完全对齐，matmul要求矩阵都是2维的，如下就可以执行：
```
>>> c
array([[ 0.,  8.],
       [-5.,  0.]], dtype=float32)
>>> d
array([[2., 3.]], dtype=float32)
>>> F.matmul(d, c)
array([[-15.,  16.]], dtype=float32)
>>> F.matmul(c, d)
```
