### ISSUE TITLE
MNN 工作台主界面出现环境配置错误？？？？

### ISSUE THREAD

**Issue by seawater668** [alibaba/MNN#1845]
我在windows10进行MMN工作台操作，参照这个https://www.yuque.com/mnn/droiug/pcl8u0，出现如下错误：
[Error] ERROR: Command errored out with exit status 1: 'C:\Users\hjq\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace\venv\Scripts\python.exe' 'C:\Users\hjq\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace\venv\lib\site-packages\pip\_vendor\pep517\_in_process.py' get_requires_for_build_wheel 'c:\users\hongji~1\appdata\local\temp\tmp1begon' Check the logs for full command output.
[Error] WARNING: You are using pip version 20.2.3; however, version 20.3.4 is available.
[Error] You should consider upgrading via the 'C:\Users\hjq\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace\venv\Scripts\python.exe -m pip install --upgrade pip' command.
[Error] Install Requirements From https://mirrors.aliyun.com/pypi/simple/Failed!!!!!!

**Comment by hande6688** [comment]
日志如下：
[2022/02/10 11:25:24.297][INFO][77940] -- [RunCode][DebugSession] send msg to WBProcess. data: c {
  data: c {
    activatePath: 'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace'
  },
  sessionName: 'PIPActivateSetupEventIdentifier',
  type: 'pip-setup-activatePath'
}
[2022/02/10 11:25:24.297][INFO][77940] -- [ChildProcess] background out [WBProcess]:onMessage. child process receives:  {
  data: {
    activatePath: 'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace'
  },
  sessionName: 'PIPActivateSetupEventIdentifier',
  type: 'pip-setup-activatePath'
}
[PIPManager] setup activate path to C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace
11:25:24.298 > [PIPManager] setup activate path to C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace

[2022/02/10 11:25:24.310][INFO][77940] -- WBProcess log [WBProcess]:onMessage. child process receives:  {
  data: {
    activatePath: 'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace'
  },
  sessionName: 'PIPActivateSetupEventIdentifier',
  type: 'pip-setup-activatePath'
}
[PIPManager] setup activate path to C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace
11:25:24.298 > [PIPManager] setup activate path to C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace

[2022/02/10 11:25:24.291][INFO][75948] -- [EasyCodepage]:initPyEnv application name: Playground
[2022/02/10 11:25:24.292][INFO][75948] -- [InstallSession]:install  mnnFace true
[2022/02/10 11:25:24.296][INFO][75948] -- install activatePath is C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace
[2022/02/10 11:25:24.315][INFO][75948] -- [InstallPython2ProcessHandler.js]::_checkLocalFileExecutable ok
[2022/02/10 11:25:24.325][INFO][75948] -- ProjectInitializeView::percent 0
[2022/02/10 11:25:24.331][INFO][75948] -- _activateVirtualEnv_activateVirtualEnv C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace
[2022/02/10 11:25:24.331][INFO][75948] -- cache path undefined
[2022/02/10 11:25:24.331][INFO][75948] -- [install_code_env.js]::_activiateVirtualEnv start C:\Users\hongjinqi\AppData\Roaming\mnnenv\pyenv\Versions\2.7\python.exe
[2022/02/10 11:25:24.423][INFO][75948] -- [InstallSession.js]::initEnv callback 2 c {
  isSuccess: true,
  message: 'Local Python Executable Already Installed',
  finished: false,
  percent: 0.2
}
[2022/02/10 11:25:24.424][INFO][75948] -- ProjectInitializeView::percent 20
[2022/02/10 11:25:26.900][INFO][75948] -- python shell [Executed]Creating virtual environement..., 0.3
created virtual environment CPython2.7.18.final.0-64 in 1751ms
[2022/02/10 11:25:26.901][INFO][75948] -- python shell   creator CPython2Windows(dest=C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace\venv, clear=False, global=False)
[2022/02/10 11:25:26.901][INFO][75948] -- python shell   seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=C:\Users\hongjinqi\AppData\Local\pypa\virtualenv)
[2022/02/10 11:25:26.902][INFO][75948] -- python shell     added seed packages: pip==20.2.3, setuptools==44.1.1, wheel==0.35.1
[2022/02/10 11:25:26.902][INFO][75948] -- python shell   activators PythonActivator,FishActivator,BatchActivator,BashActivator,PowerShellActivator
[2022/02/10 11:25:27.004][INFO][75948] -- [InstallSession.js]::initEnv callback 2 c {
  isSuccess: true,
  message: 'Creating virtual environement...',
  finished: false,
  percent: 0.3
}
[2022/02/10 11:25:27.004][INFO][75948] -- ProjectInitializeView::percent 30
[2022/02/10 11:25:30.281][INFO][75948] -- python shell [Executed]Create virtual environement successfully, 0.4
当前工作目录为 C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace
[Executed]Activate virtual env successfully, 0.5
[Executed]PIP install from https://mirrors.aliyun.com/pypi/simple/ ..., 0.6
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
[2022/02/10 11:25:30.396][INFO][75948] -- [InstallSession.js]::initEnv callback 2 c {
  isSuccess: true,
  message: 'Create virtual environement successfully',
  finished: false,
  percent: 0.4
}
[2022/02/10 11:25:30.396][INFO][75948] -- ProjectInitializeView::percent 40
[2022/02/10 11:25:32.095][INFO][75948] -- python shell Collecting jedi==0.17.2
[2022/02/10 11:25:32.101][INFO][75948] -- python shell   Using cached https://mirrors.aliyun.com/pypi/packages/c3/d4/36136b18daae06ad798966735f6c3fb96869c1be9f8245d2a8f556e40c36/jedi-0.17.2-py2.py3-none-any.whl (1.4 MB)
[2022/02/10 11:25:32.102][INFO][75948] -- [Console] flush content to disk
[2022/02/10 11:25:32.104][INFO][75948] -- [main 2022-02-10T03:25:32.104Z] [File Watcher (node.js)] [CHANGED] \tmp\mnn_console_logs\output_20220210T094212\mnn.python-env.log
[2022/02/10 11:25:32.305][INFO][75948] -- [main 2022-02-10T03:25:32.305Z] [File Watcher (node.js)] >> normalized [CHANGED] \tmp\mnn_console_logs\output_20220210T094212\mnn.python-env.log
[2022/02/10 11:25:32.784][INFO][75948] -- python shell Collecting watchdog==0.10.6
[2022/02/10 11:25:52.494][INFO][75948] -- err code signal PythonShellError:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, ''))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB43C8>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB4808>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB4F48>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='mirrors.aliyun.com', port=443): Max retries exceeded with url: /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB48C8>: Failed to establish a new connection: [Errno 10061] ',)))

WARNING: You are using pip version 20.2.3; however, version 20.3.4 is available.
You should consider upgrading via the 'C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Install Requirements From https://mirrors.aliyun.com/pypi/simple/Failed!!!!!!

    at PythonShell.parseError (C:\Users\hongjinqi\AppData\Local\Programs\MNNWorkbench\resources\app\node_modules\python-shell\index.js:269:21)
    at terminateIfNeeded (C:\Users\hongjinqi\AppData\Local\Programs\MNNWorkbench\resources\app\node_modules\python-shell\index.js:144:32)
    at ChildProcess.<anonymous> (C:\Users\hongjinqi\AppData\Local\Programs\MNNWorkbench\resources\app\node_modules\python-shell\index.js:136:13)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  executable: 'C:\\Users\\hongjinqi\\AppData\\Roaming\\mnnenv\\pyenv\\Versions\\2.7\\python.exe',
  options: [ '-u' ],
  script: 'C:\\Users\\hongjinqi\\AppData\\Local\\Programs\\MNNWorkbench\\resources\\app\\dist\\electron\\pyenv\\prepare\\install_code_env.py',
  args: [
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\venv\\Scripts\\activate.ps1',
    'C:\\Users\\hongjinqi\\AppData\\Roaming\\mnnenv\\pyenv\\Versions\\2.7\\python.exe',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\requirements.txt',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\requirements_inner.txt',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\cache',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\venv',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace',
    'https://mirrors.aliyun.com/pypi/simple/'
  ],
  exitCode: 1
} 1 null
[2022/02/10 11:25:52.495][INFO][75948] -- [install_code_env.js]::end 1 null PythonShellError:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, ''))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB43C8>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB4808>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB4F48>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='mirrors.aliyun.com', port=443): Max retries exceeded with url: /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB48C8>: Failed to establish a new connection: [Errno 10061] ',)))

WARNING: You are using pip version 20.2.3; however, version 20.3.4 is available.
You should consider upgrading via the 'C:\Users\hongjinqi\AppData\Local\MNNWorkbenchDataDistExternal\Models\mnnFace\venv\Scripts\python.exe -m pip install --upgrade pip' command.
Install Requirements From https://mirrors.aliyun.com/pypi/simple/Failed!!!!!!

    at PythonShell.parseError (C:\Users\hongjinqi\AppData\Local\Programs\MNNWorkbench\resources\app\node_modules\python-shell\index.js:269:21)
    at terminateIfNeeded (C:\Users\hongjinqi\AppData\Local\Programs\MNNWorkbench\resources\app\node_modules\python-shell\index.js:144:32)
    at ChildProcess.<anonymous> (C:\Users\hongjinqi\AppData\Local\Programs\MNNWorkbench\resources\app\node_modules\python-shell\index.js:136:13)
    at ChildProcess.emit (events.js:203:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  executable: 'C:\\Users\\hongjinqi\\AppData\\Roaming\\mnnenv\\pyenv\\Versions\\2.7\\python.exe',
  options: [ '-u' ],
  script: 'C:\\Users\\hongjinqi\\AppData\\Local\\Programs\\MNNWorkbench\\resources\\app\\dist\\electron\\pyenv\\prepare\\install_code_env.py',
  args: [
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\venv\\Scripts\\activate.ps1',
    'C:\\Users\\hongjinqi\\AppData\\Roaming\\mnnenv\\pyenv\\Versions\\2.7\\python.exe',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\requirements.txt',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\requirements_inner.txt',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\cache',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\venv',
    'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace',
    'https://mirrors.aliyun.com/pypi/simple/'
  ],
  exitCode: 1
}
[2022/02/10 11:25:52.496][INFO][75948] -- [Console] flush content to disk
[2022/02/10 11:25:52.497][INFO][75948] -- [main 2022-02-10T03:25:52.497Z] [File Watcher (node.js)] [CHANGED] \tmp\mnn_console_logs\output_20220210T094212\mnn.python-env.log
[2022/02/10 11:25:52.603][INFO][75948] -- [InstallSession.js]::initEnv callback 2 c {
  isSuccess: false,
  message: "Error:   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz\r\n" +
    "  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', error(10054, ''))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz\r\n" +
    "  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB43C8>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz\r\n" +
    "  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB4808>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz\r\n" +
    "  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB4F48>: Failed to establish a new connection: [Errno 10061] ',))': /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz\r\n" +
    "ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='mirrors.aliyun.com', port=443): Max retries exceeded with url: /pypi/packages/8e/68/261843fe0fed52c7f4364325bde666c858c582547c6a32e90ce9c184a5d7/watchdog-0.10.6.tar.gz (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000000005AB48C8>: Failed to establish a new connection: [Errno 10061] ',)))\r\n" +
    '\r\n' +
    'WARNING: You are using pip version 20.2.3; however, version 20.3.4 is available.\r\n' +
    "You should consider upgrading via the 'C:\\Users\\hongjinqi\\AppData\\Local\\MNNWorkbenchDataDistExternal\\Models\\mnnFace\\venv\\Scripts\\python.exe -m pip install --upgrade pip' command.\r\n" +
    'Install Requirements From https://mirrors.aliyun.com/pypi/simple/Failed!!!!!!\r\n',
  finished: true,
  percent: 1
}
[2022/02/10 11:25:52.621][INFO][75948] -- ProjectInitializeView::percent 100
[2022/02/10 11:25:52.713][INFO][75948] -- [main 2022-02-10T03:25:52.713Z] [File Watcher (node.js)] >> normalized [CHANGED] \tmp\mnn_console_logs\output_20220210T094212\mnn.python-env.log
[2022/02/10 11:26:06.542][INFO][75948] -- [Template::show log]
