### ISSUE TITLE
createSession() crashes when loading a model with LSTM layer

### ISSUE THREAD

**Issue by aabghari** [alibaba/MNN#1889]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux Debian-10-64bit

# Github版本:
# Github Version:
``1.2.6``

# 编译方式:
# Compiling Method

cmake
```
cmake -DMNN_USE_SYSTEM_LIB=OFF -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_SEP_BUILD=OFF -DMNN_BUILD_DEMO=OFF -DMNN_BUILD_TOOLS=ON -DMNN_BUILD_CONVERTER=ON -DMNN_EVALUATION=OFF -DMNN_OPENCL=OFF -DMNN_OPENGL=OFF -DMNN_VULKAN=OFF -DMNN_AVX512=ON -DMNN_ARM82=OFF -DMNN_SUPPORT_BF16=OFF ../
```

I am converting the attached onnx model to MNN format:
``MNNConvert -f ONNX --model.onnx --MNNModel model.mnn --bizCode MNN``, however it crashes when loading the model.

```
#0  0x000055555568d3b0 in MNN::TensorUtils::getDescribe(MNN::Tensor const*) ()
#1  0x00005555556b9af3 in MNN::GeometryComputerUtils::makeRaster(MNN::CommandBuffer const&, MNN::CommandBuffer&, MNN::GeometryComputer::Context&) ()
#2  0x00005555556ba0d0 in MNN::GeometryComputerUtils::shapeComputeAndGeometryTransform(std::vector<MNN::Schedule::PipelineInfo, std::allocator<MNN::Schedule::PipelineInfo> >&, MNN::GeometryComputer::Context&, std::shared_ptr<MNN::Backend>, MNN::Runtime::CompilerType) ()
#3  0x000055555567f1b8 in MNN::Pipeline::encode(bool, bool) ()
#4  0x0000555555686a97 in MNN::Session::resize(bool) ()
#5  0x000055555566f253 in MNN::Interpreter::createMultiPathSession(std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&, std::pair<std::map<MNNForwardType, std::shared_ptr<MNN::Runtime>, std::less<MNNForwardType>, std::allocator<std::pair<MNNForwardType const, std::shared_ptr<MNN::Runtime> > > >, std::shared_ptr<MNN::Runtime> > const&) ()
#6  0x000055555566f335 in MNN::Interpreter::createMultiPathSession(std::vector<MNN::ScheduleConfig, std::allocator<MNN::ScheduleConfig> > const&) ()
#7  0x000055555566fd44 in MNN::Interpreter::createSession(MNN::ScheduleConfig const&) ()
```
[model.onnx.zip](https://github.com/alibaba/MNN/files/8328205/model.onnx.zip)

**Comment by jxt1234** [comment]
Fixed by. 951a57b07c34acd31f3687d6225c674d0c53a211
