### ISSUE TITLE
Exception: initMNN.expr: PyType_Ready PyMNNVarType failed

### ISSUE THREAD

**Issue by justinge** [alibaba/MNN#2068]
9.15日编辑安装的最新MNN，
9.19 pip install的 mnn
python 环境
Python 3.8.12
centos7.9

然而报错
```
>>> import MNN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jianming_ge/.local/lib/python3.8/site-packages/MNN/__init__.py", line 4, in <module>
    from _mnncengine import *
Exception: initMNN.expr: PyType_Ready PyMNNVarType failed

**Comment by wangzhaode** [comment]
是numpy版本不正确导致的，请重新安装numpy试一下

**Comment by wangzhaode** [comment]
该问题已修复，下版本会发布
