### ISSUE TITLE
convert ONNX model into MNN mode failed

### ISSUE THREAD

**Issue by MaybeShewill-CV** [alibaba/MNN#2395]
# 平台(如果交叉编译请再附上交叉编译目标平台):  Linux Ubuntu 20.04
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

# MNN Version MNN-2.3.0 release version

running python ../tools/script/testMNNFromOnnx.py sam_vit_l_decoder.onnx failed.

Here is script's output

```
Dir exist
onnx/test.onnx
2023-05-25 14:28:14.513721600 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:566 CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements to ensure all dependencies are met.
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
tensor(float)
['masks', 'iou_predictions', 'low_res_masks']
inputs:
image_embeddings
onnx/
point_coords
onnx/
point_labels
onnx/
mask_input
onnx/
has_mask_input
onnx/
orig_im_size
onnx/
2023-05-25 14:28:16.688644956 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running Resize node. Name:'Resize_1121' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:289 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale > 0 was false. Scale value should be greater than 0.

Traceback (most recent call last):
  File "../tools/script/testMNNFromOnnx.py", line 283, in <module>
    t.Test()
  File "../tools/script/testMNNFromOnnx.py", line 259, in Test
    self.__run_onnx()
  File "../tools/script/testMNNFromOnnx.py", line 168, in __run_onnx
    outputs = ort_session.run(None, inputs)
  File "/anaconda3/envs/pytorch/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Resize node. Name:'Resize_1121' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/upsamplebase.h:289 void onnxruntime::UpsampleBase::ScalesValidation(const std::vector<float>&, onnxruntime::UpsampleMode) const scale > 0 was false. Scale value should be greater than 0.
```

onnx model can be loaded and inference successfully via onnxruntime. Plz help :)

**Comment by jxt1234** [comment]
The error is caused by onnxruntime can't run random inputs.Change the input in testMNNFromOnnx.py.

**Comment by MaybeShewill-CV** [comment]
@jxt1234 Thanks for replaying. Are you saying that changing the input data from random numbers to real data can fix this issue? ：）

**Comment by jxt1234** [comment]
> @jxt1234 Thanks for replaying. Are you saying that changing the input data from random numbers to real data can fix this issue? ：）

yes

**Comment by MaybeShewill-CV** [comment]
@jxt1234 MNN-2.5.0 testMNNFromOnnx.py runs successfully :)

**Comment by hajungong007** [comment]
> api.onnxruntime_pybind

hi，我用MNN-2.5.0跑报错， onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Resize node. Name:'/Resize_1' Status Message: upsamplebase.h:334 onnxruntime::UpsampleBase::ScalesValidation Scale value should be greater than 0.
请问你是怎么解决的？

**Comment by MaybeShewill-CV** [comment]
@hajungong007 测试的输入数据可以使用np.ones代替随机数:)
