### ISSUE TITLE
MNNConvert 转换BLIP的txt_decoder ONNX模型出错

### ISSUE THREAD

**Issue by w313062006** [alibaba/MNN#2669]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
ubuntu 22.04

# Github版本:
# Github Version:
2.7.0 和 2.7.1

# 编译方式:
# Compiling Method
```
cmake .. -DMNN_BUILD_CONVERTER=true && make -j4
```

# 转换日志:
# Build Log:

```
root@System-Product-Name:~/Projects/MNN/build$ ./MNNConvert -f ONNX --modelFile ../../onnx_model/txt_decoder.onnx --MNNModel txt_decoder.mnn --bizCode biz
The device support i8sdot:0, support fp16:0, support i8mm: 0
Start to Convert Other Model Format To MNN Model..., target version: 2.7
[14:47:52] /home/wushaung3/Projects/MNN/tools/converter/source/onnx/onnxConverter.cpp:46: ONNX Model ir version: 8
[14:47:52] /home/wushaung3/Projects/MNN/tools/converter/source/onnx/onnxConverter.cpp:47: ONNX Model opset version: 17
Start to Optimize the MNN Net...
AddressSanitizer:DEADLYSIGNAL
=================================================================
==6001==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x7f30d4be1f7b bp 0x0fffd8ae3adc sp 0x7ffec571d6a0 T0)
==6001==The signal is caused by a READ memory access.
==6001==Hint: address points to the zero page.
    #0 0x7f30d4be1f7b in MNN::Express::_Range(MNN::Express::VARP, MNN::Express::VARP, MNN::Express::VARP) (/home/wushaung3/Projects/MNN/build/express/libMNN_Express.so+0x1e1f7b)
    #1 0x7f30d5d27be6 in MNN::Express::OnnxLayerNormTransform::onExecute(std::shared_ptr<MNN::Express::Expr>) const (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xf27be6)
    #2 0x7f30d5d788b1 in std::_Function_handler<bool (std::shared_ptr<MNN::Express::Expr>), MNN::Express::gRegister::{lambda()#1}::operator()() const::{lambda(std::shared_ptr<MNN::Express::Expr>)#2}>::_M_invoke(std::_Any_data const&, std::shared_ptr<MNN::Express::Expr>&&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xf788b1)
    #3 0x7f30d59cf931 in std::_Function_handler<bool (std::shared_ptr<MNN::Express::Expr>), MNN::Express::TemplateMerge::insertTemplate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::function<bool (std::shared_ptr<MNN::Express::Expr>)>, std::function<bool (std::shared_ptr<MNN::Express::Expr>)>, MNN::Express::PassPriority)::{lambda(std::shared_ptr<MNN::Express::Expr>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<MNN::Express::Expr>&&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xbcf931)
    #4 0x7f30d59e12a5 in MNN::Express::TemplateMerge::onExecute(std::vector<MNN::Express::VARP, std::allocator<MNN::Express::VARP> > const&, MNN::Express::PassPriority, std::vector<MNN::Express::VARP, std::allocator<MNN::Express::VARP> > const&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xbe12a5)
    #5 0x7f30d5988b33 in MNN::Express::RunExtraPass(std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, MNN::Express::VARP, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, MNN::Express::VARP> > > const&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xb88b33)
    #6 0x7f30d5992ce6 in MNN::Express::optimizeNetImpl(std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, MNN::Express::VARP, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, MNN::Express::VARP> > > const&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xb92ce6)
    #7 0x7f30d5981afb in std::_Function_handler<std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> > (std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, MNN::Express::VARP, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, MNN::Express::VARP> > > const&), std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> > (*)(std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, MNN::Express::VARP, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, MNN::Express::VARP> > > const&)>::_M_invoke(std::_Any_data const&, std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> >&, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, MNN::Express::VARP, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, MNN::Express::VARP> > > const&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xb81afb)
    #8 0x7f30d59ae984 in optimizeNet(std::unique_ptr<MNN::NetT, std::default_delete<MNN::NetT> >&, bool, modelConfig&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0xbae984)
    #9 0x7f30d53c6a1b in MNN::Cli::convertModel(modelConfig&) (/home/wushaung3/Projects/MNN/build/tools/converter/libMNNConvertDeps.so+0x5c6a1b)
    #10 0x55c8f8687e91 in main (/home/wushaung3/Projects/MNN/build/MNNConvert+0x1e91)
    #11 0x7f30d0029d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #12 0x7f30d0029e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #13 0x55c8f8688184 in _start (/home/wushaung3/Projects/MNN/build/MNNConvert+0x2184)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/home/wushaung3/Projects/MNN/build/express/libMNN_Express.so+0x1e1f7b) in MNN::Express::_Range(MNN::Express::VARP, MNN::Express::VARP, MNN::Express::VARP)
==6001==ABORTING
```

ONNX模型是没问题的，已经用python测试过了。社区对这个错误有什么建议么？

**Comment by jxt1234** [comment]
更新 MNN 代码，2.8.0 已经修正

**Comment by w313062006** [comment]
cool, it's ok
