### ISSUE TITLE
同一个模型，2.8.0版本模型转换失败而2.1.0转换成功

### ISSUE THREAD

**Issue by xingxinghanzi** [alibaba/MNN#2727]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  

# Github版本:
# Github Version:

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
 cmake .. -G Ninja -DMNN_BUILD_CONVERTER=ON -DMNN_BUILD_SHARED_LIBS=OFF -DMNN_WIN_RUNTIME_MT=ON
```

# 编译日志:
# Build Log:

![49fa7bff51051bbdcaa2aec73d18a871](https://github.com/alibaba/MNN/assets/71701360/7433b265-bc87-4455-9f99-7e77be4023f3)
![8e150f223adc4c98a99f3e175512bfd9](https://github.com/alibaba/MNN/assets/71701360/a8fc7fbf-868f-4f57-bdd7-943cb510305d)

```
（cmd）python D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py D:\workspace\mnn_experiments\mobilenet_xx_sim.onnx DEBUG
onnx\test.onnx
tensor(float)
tensor(float)
['score', 'feats']
inputs:
images
onnx/
onnx/
outputs:
onnx/onnx::Conv_338.txt (1, 120, 14, 14)
onnx/
Traceback (most recent call last):
  File "D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py", line 282, in <module>
    t.Debug()
  File "D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py", line 270, in Debug
    self.__binary_search(left_id, right_id)
  File "D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py", line 243, in __binary_search
    if self.__test_specify_output(self.node_output[test_node][0]):
  File "D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py", line 189, in __test_specify_output
    res = self.Test()
  File "D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py", line 263, in Test
    self.__run_onnx()
  File "D:\MNN_compile\MNN-2.8.0\tools\script\testMNNFromOnnx.py", line 179, in __run_onnx
    f = open(name, 'w')
OSError: [Errno 22] Invalid argument: 'onnx/onnx::Conv_338.txt'

```

**Comment by xingxinghanzi** [comment]
mnn2.8.1也转模型失败了
![1705053029067_50098912-D537-4ec2-A8B4-87415516D30D](https://github.com/alibaba/MNN/assets/71701360/9d6af2d3-c35c-442a-b50e-a61940b6e0a0)

**Comment by v0jiuqi** [comment]
报错说了，没有这个文件。。

**Comment by xingxinghanzi** [comment]
@v0jiuqi 这个节点onnx/onnx::Conv_338不是输入节点，逻辑上本来就不存在这个文件
