### ISSUE TITLE
请问有没有关于支持BERT类型模型的计划？

### ISSUE THREAD

**Issue by DamonsJ** [alibaba/MNN#2777]
自己转出的BERT模型，运行的时候报错，我看了一下输出tensor的所有的dim都是0
请问有没有官方的BERT模型的支持呢？

**Comment by jxt1234** [comment]
Bert 模型 MNN 支持的，这个大概率是你没有 resizeTensor -> resizeSession ，或者用 module api ，请先看文档 https://mnn-docs.readthedocs.io/en/latest/

检查 mnn 是否支持用 testMNNFromOnnx.py 等脚本测试

**Comment by DamonsJ** [comment]
我是用的这个下面的bert模型onnx：
https://huggingface.co/google-bert/bert-base-uncased/tree/main

运行testMNNFromOnnx.py
报下面的错误

Dir exist
onnx/test.onnx
tensor(int64)
tensor(int64)
tensor(int64)
['logits']
inputs:
input_ids
onnx/
attention_mask
onnx/
token_type_ids
onnx/
2024-03-08 14:28:59.011568 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running Gather node. Name:'/bert/embeddings/token_type_embeddings/Gather' Status Message: indices element out of data bounds, idx=7 must be within the inclusive range [-2,1]
Traceback (most recent call last):
  File "/Users/honglei.sun/Documents/OpenSource/MNN/build/./testMNNFromOnnx.py", line 287, in <module>
    t.Test()
  File "/Users/honglei.sun/Documents/OpenSource/MNN/build/./testMNNFromOnnx.py", line 263, in Test
    self.__run_onnx()
  File "/Users/honglei.sun/Documents/OpenSource/MNN/build/./testMNNFromOnnx.py", line 172, in __run_onnx
    outputs = ort_session.run(None, inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Gather node. Name:'/bert/embeddings/token_type_embeddings/Gather' Status Message: indices element out of data bounds, idx=7 must be within the inclusive range [-2,1]

**Comment by DamonsJ** [comment]
@jxt1234 

https://huggingface.co/distilbert/distilbert-base-cased/tree/main
这个也是一样的，用./testMNNFromOnnx.py 是成功的
用./MNNV2Basic.out 是失败的
timeprofile也是失败的

./MNNV2Basic.out /Users/honglei.sun/Documents/OpenSource/mnn-llm/distilbert-base-cased/distil-bert-cased.mnn 10 2 0 4 3 "input_ids:1x128,attention_mask:1x128"
Save AllTensors to output/*.txt
Use extra forward type: 0
0 128 128 
Open Model /Users/honglei.sun/Documents/OpenSource/mnn-llm/distilbert-base-cased/distil-bert-cased.mnn
Load Cache file error.
The device support i8sdot:0, support fp16:0, support i8mm: 0
===========> Resize Again...
Compute Shape Error for BinaryOp37
test_main, 282, cost time: 63.341003 ms
Resize error, can't execute MNN
