### ISSUE TITLE
MNN Llama-3-8B-Instruct export 失败

### ISSUE THREAD

**Issue by quinlan-w** [alibaba/MNN#2876]
commit 6a22d17aa9841dd8ed66f37a704bc9bfc7605555
export LLama3 遇到如下报错：
python transformers/llm/export/llm_export.py --path /swtest/LLM/Meta-Llama-3-8B/  --embed_bin --embed_bf16 --export_embed --export_token --export --skip_slim --type Llama-3-8B-Instruct
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.51it/s]
Traceback (most recent call last):
  File "/data//code_llm/MNN/transformers/llm/export/llm_export.py", line 1255, in <module>
    llm_exporter = llm_models[model_type](args)
  File "/data/g/code_llm/MNN/transformers/llm/export/llm_export.py", line 913, in __init__
    super().__init__(args)
  File "/data//code_llm/MNN/transformers/llm/export/llm_export.py", line 115, in __init__
    self.load_model()
  File "/data//code_llm/MNN/transformers/llm/export/llm_export.py", line 925, in load_model
    if hasattr(model, 'generation_config'):
NameError: name 'model' is not defined

**Comment by quinlan-w** [comment]
Qwen-1_8B-Chat 同样export 失败，是我环境问题吗？
python transformers/llm/export/llm_export.py --path /swtest/LLM/Qwen-1_8B-Chat/  --embed_bin --embed_bf16 --export_embed --export_token --export --skip_slim --type Qwen-1_8B-Chat
TypeError: QWenBlock.forward() got an unexpected keyword argument 'rotary_pos_emb'

pip list：
accelerate                    0.30.1
certifi                       2024.2.2
charset-normalizer            3.3.2
coloredlogs                   15.0.1
einops                        0.8.0
filelock                      3.14.0
flatbuffers                   24.3.25
fsspec                        2024.5.0
huggingface-hub               0.23.0
humanfriendly                 10.0
idna                          3.7
Jinja2                        3.1.4
loguru                        0.7.2
MarkupSafe                    2.1.5
mpmath                        1.3.0
networkx                      3.3
numpy                         1.26.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.20.5
nvidia-nvjitlink-cu12         12.4.127
nvidia-nvtx-cu12              12.1.105
onnx                          1.16.0
onnxruntime                   1.18.0
onnxslim                      0.1.26
packaging                     24.0
peft                          0.11.1
pip                           24.0
protobuf                      5.26.1
psutil                        5.9.8
PyYAML                        6.0.1
regex                         2024.5.15
requests                      2.31.0
safetensors                   0.4.3
sentencepiece                 0.2.0
setuptools                    69.5.1
sympy                         1.12
tiktoken                      0.7.0
tokenizers                    0.19.1
torch                         2.3.0
tqdm                          4.66.4
transformers                  4.41.0
transformers-stream-generator 0.0.5
triton                        2.3.0
typing_extensions             4.11.0
urllib3                       2.2.1
wheel                         0.43.0
