### ISSUE TITLE
使用mnn_offline_quant.py时，执行到quant_func方法的net.forward时候报错了Tensorflow's interp's shape should be length two, Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by githubpeichao** [alibaba/MNN#2920]
# 平台(如果交叉编译请再附上交叉编译目标平台):  linux x86, ubuntu 18.04
# Platform(Include target platform as well if cross-compiling):  

# Github版本: master分支
# Github Version: tag 2.8.1
# comment = d284430f92557aa8b4cc435752b1dff3309f2e38

直接下载ZIP包请提供下载日期以及压缩包注释里的git版本(可通过``7z l zip包路径``命令并在输出信息中搜索``Comment`` 获得，形如``Comment = bc80b11110cd440aacdabbf59658d630527a7f2b``)。 git clone请提供 ``git commit`` 第一行的commit id

Provide date (or better yet, git revision from the comment section of the zip. Obtainable using ``7z l PATH/TO/ZIP`` and search for ``Comment`` in the output) if downloading source as zip,otherwise provide the first commit id from the output of ``git commit``

# 编译方式:
# Compiling Method

```
请在这里粘贴cmake参数或使用的cmake脚本路径以及完整输出
Paste cmake arguments or path of the build script used here as well as the full log of the cmake proess here or pastebin
```

# 编译日志:
# Build Log:

```
粘贴在这里
Paste log here or pastebin
```

**Comment by githubpeichao** [comment]
看起来是到c++的代码了，我该如何往下排查

**Comment by githubpeichao** [comment]
使用gdb打印出来的堆栈日志
`0x00007fffe7ef27b1 in MNN::Express::ConvBNReluFusedModule::fakeQuantFeatureWithMinMax(MNN::Express::VARP, MNN::Express::VARP, MNN::Express::VARP, MNN::Express::VARP, std::vector<int, std::allocator<int> >) ()
   from /home/ubuntu/miniconda3/envs/mnn/lib/python3.7/site-packages/_mnncengine.cpython-37m-x86_64-linux-gnu.so
(gdb) backtrace
#0  0x00007fffe7ef27b1 in MNN::Express::ConvBNReluFusedModule::fakeQuantFeatureWithMinMax(MNN::Express::VARP, MNN::Express::VARP, MNN::Express::VARP, MNN::Express::VARP, std::vector<int, std::allocator<int> >) ()
   from /home/ubuntu/miniconda3/envs/mnn/lib/python3.7/site-packages/_mnncengine.cpython-37m-x86_64-linux-gnu.so
#1  0x00007fffe7f0b329 in MNN::Express::ConvBNReluFusedModule::onForward(std::vector<MNN::Express::VARP, std::allocator<MNN::Express::VARP> > const&) () from /home/ubuntu/miniconda3/envs/mnn/lib/python3.7/site-packages/_mnncengine.cpython-37m-x86_64-linux-gnu.so
#2  0x00007fffe7e1b0e2 in MNN::Express::PipelineModule::onForward(std::vector<MNN::Express::VARP, std::allocator<MNN::Express::VARP> > const&) () from /home/ubuntu/miniconda3/envs/mnn/lib/python3.7/site-packages/_mnncengine.cpython-37m-x86_64-linux-gnu.so
#3  0x00007fffe7b55629 in PyMNN_Module_forward (self=<optimized out>, args=<optimized out>) at /opt/rh/devtoolset-10/root/usr/include/c++/10/bits/shared_ptr_base.h:1324
#4  0x00005555556cbf40 in _PyMethodDef_RawFastCallKeywords ()
#5  0x00005555556cc14f in _PyMethodDescr_FastCallKeywords ()
#6  0x0000555555727fa9 in _PyEval_EvalFrameDefault ()
#7  0x00005555556cb07b in _PyFunction_FastCallKeywords ()
#8  0x0000555555723a66 in _PyEval_EvalFrameDefault ()
#9  0x00005555556cb07b in _PyFunction_FastCallKeywords ()
#10 0x0000555555723a66 in _PyEval_EvalFrameDefault ()
#11 0x0000555555669059 in _PyEval_EvalCodeWithName ()
#12 0x0000555555669f24 in PyEval_EvalCodeEx ()
#13 0x0000555555669f4c in PyEval_EvalCode ()
#14 0x0000555555782a14 in run_mod ()
#15 0x000055555578bf11 in PyRun_FileExFlags ()
#16 0x000055555578c104 in PyRun_SimpleFileExFlags ()
#17 0x000055555578dbbd in pymain_main.constprop ()
#18 0x000055555578de30 in _Py_UnixMain ()
#19 0x00007ffff7ccb0b3 in __libc_start_main (main=0x555555649d20 <main>, argc=8, argv=0x7fffffffd638, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd628) at ../csu/libc-start.c:308
#20 0x0000555555733052 in _start () at ../sysdeps/x86_64/elf/start.S:103`
