### ISSUE TITLE
使用 mnnconvert 转换失败,  目标目录没有输出任何文件, 只在当前目录留下一个 1.8G 左右的 .__convert_external_data.bin 文件

### ISSUE THREAD

**Issue by joeqi0370** [alibaba/MNN#3066]
环境:
Windows 10
Python 3.10
用的是 https://pypi.doubanio.com/simple/ 源
mnn (2.9.6)
numpy (1.26.3)

此前, 用llmexport把一个tf的模型(.safetensors)转成了一个onnx
![56418653a49b2e8d4a9cce4da12991df](https://github.com/user-attachments/assets/a2250439-733e-4eed-a18f-0075e4df93f9)

运行mnnconvert把onnx转为mnn, 命令为:
`mnnconvert -f ONNX --modelFile ./model/onnx/llm.onnx --MNNModel ./model_mnn/llm.mnn --bizCode MNN --transformerFuse`

输出为:

```
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
The device supports: i8sdot:0, fp16:0, i8mm: 0, sve2: 0
Start to Convert Other Model Format To MNN Model..., 
target version: 2.9[12:33:13] @ 46: ONNX Model ir version: 10
[12:33:13] @ 47: ONNX Model opset version: 15
Start to Optimize the MNN Net...
Fuse Attention as /Reshape_4_output_0
Fuse Attention as /Reshape_9_output_0
Fuse Attention as /Reshape_14_output_0
Fuse Attention as /Reshape_19_output_0
Fuse Attention as /Reshape_24_output_0
Fuse Attention as /Reshape_29_output_0
Fuse Attention as /Reshape_34_output_0
Fuse Attention as /Reshape_39_output_0
Fuse Attention as /Reshape_44_output_0
Fuse Attention as /Reshape_49_output_0
Fuse Attention as /Reshape_54_output_0
Fuse Attention as /Reshape_59_output_0
Fuse Attention as /Reshape_64_output_0
Fuse Attention as /Reshape_69_output_0
Fuse Attention as /Reshape_74_output_0
Fuse Attention as /Reshape_79_output_0
Fuse Attention as /Reshape_84_output_0
Fuse Attention as /Reshape_89_output_0
Fuse Attention as /Reshape_94_output_0
Fuse Attention as /Reshape_99_output_0
Fuse Attention as /Reshape_104_output_0
Fuse Attention as /Reshape_109_output_0
Fuse Attention as /Reshape_114_output_0
Fuse Attention as /Reshape_119_output_0
Remove past KV for presents
```

输出上面的信息后, 就退出了.  最后只在目录下生成一个1.8G的 .__convert_external_data.bin 文件, 没有在 model_mnn 的文件夹内输出文件
![6bed6dbd9df4a4cf0db29846fa229dd4](https://github.com/user-attachments/assets/3dc2179f-24bc-4817-94c0-a1dc2af33eee)

请问可能是什么问题导致的?

**Comment by joeqi0370** [comment]
1. 使用 lmm_export.py 导出 mnn 的话, 会出错:
```
Traceback (most recent call last):
  File "D:\GOT-OCR2.0\mnn-llm\mnn-llm-GOT-OCR2.0\export\llmexport.py", line 1924, in <module>
    main()
  File "D:\GOT-OCR2.0\mnn-llm\mnn-llm-GOT-OCR2.0\export\llmexport.py", line 1921, in main
    llm_exporter.export(args.export)
  File "D:\GOT-OCR2.0\mnn-llm\mnn-llm-GOT-OCR2.0\export\llmexport.py", line 1557, in export
    MNNConveter(visual_onnx, None, self).export(quant_bit=self.visual.quant_bit)
  File "D:\Python\Anaconda3\envs\got\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GOTVisiual' object has no attribute 'quant_bit'
```

命令行为:
`python llmexport.py --path "D:\GOT-OCR2.0\mnn-llm\GOT_weights" --export mnn --dst_path "./model_mnn/"`

是不是不支持这个模型  Qwen2ForCausalLM

D盘有300GB剩余空间

**Comment by joeqi0370** [comment]
改为在Linux下运行就没有问题了

**Comment by harrymore** [comment]
我也遇到这个问题，windows 自己编译的版本，2.7.1。后面我用python的pip装了最新版（3.0.0）的就解决了这个问题
