### ISSUE TITLE
android报错No implementation  MNNNetNative

### ISSUE THREAD

**Issue by CangHaiQingYue** [alibaba/MNN#3139]
你好，我在尝试android demo的时候，报错：
`No implementation found for long com.example.mnn.MNNNetNative.nativeCreateNetFromFile(java.lang.String) (tried Java_com_example_mnn_MNNNetNative_nativeCreateNetFromFile and Java_com_example_mnn_MNNNetNative_nativeCreateNetFromFile__Ljava_lang_String_2)
2024-12-26 11:22:40.460 21060-21060 AndroidRuntime          com.example.javacvtest               E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.javacvtest, PID: 21060
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for long com.example.mnn.MNNNetNative.nativeCreateNetFromFile(java.lang.String) (tried Java_com_example_mnn_MNNNetNative_nativeCreateNetFromFile and Java_com_example_mnn_MNNNetNative_nativeCreateNetFromFile__Ljava_lang_String_2)
                                                                                                    	at com.example.mnn.MNNNetNative.nativeCreateNetFromFile(Native Method)
                                                                                                    	at com.example.mnn.MNNNetInstance.createFromFile(MNNNetInstance.java:10)
                                                                                                    	at com.example.javacvtest.MainActivity.initializeOpenCVDependencies(MainActivity.java:211)
                                                                                                    	at com.example.javacvtest.MainActivity.access$000(MainActivity.java:89)
                                                                                                    	at com.example.javacvtest.MainActivity$1.onManagerConnected(MainActivity.java:134)
                                                                                                    	at com.example.javacvtest.MainActivity.onResume(MainActivity.java:124)
                                                                                                    	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1457)
                                                                                                    	at android.app.Activity.performResume(Activity.java:8298)`

相关的.so文件libs文件我已经放到了app/libs/目录下，请问还需要配置哪些路径吗？
![image](https://github.com/user-attachments/assets/bb2c7964-a2c9-41e5-b403-e5de201c18d0)

**Comment by jxt1234** [comment]
应该是 Java 层没有调 System.load ，或者 load 时报错了。看下前面的 log
