### ISSUE TITLE
Android demo crash

### ISSUE THREAD

**Issue by gasgallo** [alibaba/MNN#441]
I'm trying to run the android demo, but the app crashes during opening with the following log:
```
2019-11-06 10:48:37.924 22391-22391/? I/art: Late-enabling -Xcheck:jni
2019-11-06 10:48:37.924 22391-22391/? E/art: setrlimit(RLIMIT_CORE) failed for pid 22391: Operation not permitted
2019-11-06 10:48:38.019 22391-22391/com.taobao.android.mnndemo W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art: Rejecting re-init on previously-failed class java.lang.Class<android.support.v4.view.ViewCompat$OnUnhandledKeyEventListenerWrapper>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void com.taobao.android.mnndemo.VideoActivity.onCreate(android.os.Bundle) (VideoActivity.java:177)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6709)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2624)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1483)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6141)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:912)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:802)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.taobao.android.mnndemo-2/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.android.mnndemo-2/lib/arm, /data/app/com.taobao.android.mnndemo-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v4.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, android.support.v4.view.OnApplyWindowInsetsListener) (ViewCompat.java:2203)
2019-11-06 10:48:38.040 22391-22391/com.taobao.android.mnndemo I/art:     at android.view.ViewGroup android.support.v7.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:637)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:518)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v7.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:466)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.support.v7.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:140)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void com.taobao.android.mnndemo.VideoActivity.onCreate(android.os.Bundle) (VideoActivity.java:177)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6709)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1118)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2624)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2732)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1483)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.os.Looper.loop() (Looper.java:154)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6141)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:912)
2019-11-06 10:48:38.041 22391-22391/com.taobao.android.mnndemo I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:802)
2019-11-06 10:48:38.098 22391-22391/com.taobao.android.mnndemo D/AndroidRuntime: Shutting down VM
2019-11-06 10:48:38.098 22391-22391/com.taobao.android.mnndemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.taobao.android.mnndemo, PID: 22391
    java.lang.RuntimeException: Unable to resume activity {com.taobao.android.mnndemo/com.taobao.android.mnndemo.VideoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3435)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3475)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2738)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.Camera.setDisplayOrientation(int)' on a null object reference
        at com.taobao.android.mnndemo.CameraView.setCameraDisplayOrientation(CameraView.java:166)
        at com.taobao.android.mnndemo.CameraView.openCamera(CameraView.java:68)
        at com.taobao.android.mnndemo.CameraView.onResume(CameraView.java:170)
        at com.taobao.android.mnndemo.VideoActivity.onResume(VideoActivity.java:510)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6813)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3412)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3475) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2738) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6141) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802) 
2019-11-06 10:48:38.099 22391-22407/com.taobao.android.mnndemo D/vulkan: searching for layers in '/data/app/com.taobao.android.mnndemo-2/lib/arm'
2019-11-06 10:48:38.100 22391-22407/com.taobao.android.mnndemo D/vulkan: searching for layers in '/data/app/com.taobao.android.mnndemo-2/base.apk!/lib/armeabi-v7a'
2019-11-06 10:48:38.105 22391-22407/com.taobao.android.mnndemo I/mali_so: [File] : hardware/arm/mali_so_src_of_midgard/driver/product/base/src/mali_base_kbase.c; [Line] : 876; [Func] : base_context_deal_with_version_affairs_rk_ext;
    arm_release_ver of this mali_so is 'r18p0-01rel0', rk_so_ver is '5@0'.
2019-11-06 10:48:38.105 22391-22407/com.taobao.android.mnndemo D/mali_so: [File] : hardware/arm/mali_so_src_of_midgard/driver/product/base/src/mali_base_kbase.c; [Line] : 881; [Func] : base_context_deal_with_version_affairs_rk_ext;
    current process is NOT sf, to bail out.
2019-11-06 10:48:38.123 22391-22407/com.taobao.android.mnndemo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 22407 (MNNNet)
```
Camera object is null for some reason.
Any idea?

**Comment by gasgallo** [comment]
In the end it was MNN problem, not camera problem. I rebuilt MNN for android and changed ABI target in the app and the demo is finally working.
