### ISSUE TITLE
MNN python 安装后无法调用：Symbol not found: _deflate

### ISSUE THREAD

**Issue by DarrenIm** [alibaba/MNN#540]
OS: macOS
python version：3.5
python installed from：Anaconda

安装过程：
1. brew install graphviz
2.pip install -U MNN

问题：
```
(tensorflow_cpu) ➜  ~ mnnconvert:
Traceback (most recent call last):
  File "/anaconda3/envs/tensorflow_cpu/bin/mnnconvert", line 7, in <module>
    from MNNTools.mnnconvert import main
  File "/anaconda3/envs/tensorflow_cpu/lib/python3.5/site-packages/MNNTools/mnnconvert.py", line 7, in <module>
    import Tools
ImportError: dlopen(/anaconda3/envs/tensorflow_cpu/lib/python3.5/site-packages/Tools.cpython-35m-darwin.so, 2): Symbol not found: _deflate
  Referenced from: /anaconda3/envs/tensorflow_cpu/lib/python3.5/site-packages/Tools.cpython-35m-darwin.so
  Expected in: flat namespace
 in /anaconda3/envs/tensorflow_cpu/lib/python3.5/site-packages/Tools.cpython-35m-darwin.so
```

**Comment by FzuGsr** [comment]
我也碰到这个问题，请问大佬解决了吗？

**Comment by stanleywang8888** [comment]
part-of Mac phone does not contain zlib, you need to install lib on your platform.

**Comment by stanleywang8888** [comment]
zlib is a native lib, and only part-of Mac device does not contain it. install this native lib will solve this issue.

**Comment by strivehub** [comment]
> zlib is a native lib, and only part-of Mac device does not contain it. install this native lib will solve this issue.我也碰到了，但是安装了zlib和添加环境变量，还是报错
