### ISSUE TITLE
Android build Problem 

### ISSUE THREAD

**Issue by yousefabohend** [alibaba/MNN#616]
Hi everyone I have came across with this error when i try to run android demo, I couldn't find any solutions online is there any chance it's related with repo. Here is my error below:

org.gradle.internal.UncheckedException: Build command failed.
Error while executing process C:\Users\..\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\..\Desktop\MNN-master\demo\android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target mnncore}

ninja: error: '../../../../libs/armeabi-v7a/libMNN.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmnncore.so', missing and no known rule to make it

	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:63)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:143)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:40)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:24)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:46)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:49)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:40)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:33)
	at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:355)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:219)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:68)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Build command failed.
Error while executing process C:\Users\..\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\Users\..\Desktop\MNN-master\demo\android\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target mnncore}

ninja: error: '../../../../libs/armeabi-v7a/libMNN.so', needed by '../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libmnncore.so', missing and no known rule to make it

	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:78)
	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:119)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:327)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	... 128 more

**Comment by yehorchankov** [comment]
Hello @yousefabohend ! I have tried to run android demo on linux and got the same error. I fixed it by creating `MNN/dome/android/app/libs/rmeabi-v7a/` directory and copying there the content from `MNN/project/android/build_32/` directory, which you create while building the libraries for android.

However, now I have another error during building:

```
Build command failed.
Error while executing process sdk_root/cmake/3.6.4111459/bin/cmake with arguments {--build MNN_root/demo/android/app/.externalNativeBuild/cmake/debug/x86 --target mnncore}
[1/3] Building CXX object CMakeFiles/mnncore.dir/src/main/jni/mnnnetnative.cpp.o
[2/3] Building CXX object CMakeFiles/mnncore.dir/src/main/jni/mnnportraitnative.cpp.o
[3/3] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/x86/libmnncore.so
FAILED: : && sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=i686-none-linux-android21 --gcc-toolchain=sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fopenmp -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math -fno-rtti -fno-exceptions -flax-vector-conversions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libmnncore.so -o ../../../../build/intermediates/cmake/debug/obj/x86/libmnncore.so CMakeFiles/mnncore.dir/src/main/jni/mnnnetnative.cpp.o CMakeFiles/mnncore.dir/src/main/jni/mnnportraitnative.cpp.o  ../../../../libs/x86/libMNN.so sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/21/liblog.so sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/i686-linux-android/21/libjnigraphics.so -latomic -lm && :
sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: error: ../../../../libs/x86/libMNN.so: incompatible target
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:20: error: undefined reference to 'MNN::Interpreter::createFromFile(char const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:31: error: undefined reference to 'MNN::Interpreter::~Interpreter()'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:76: error: undefined reference to 'MNN::Interpreter::createSession(MNN::ScheduleConfig const&)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:86: error: undefined reference to 'MNN::Interpreter::releaseSession(MNN::Session*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:94: error: undefined reference to 'MNN::Interpreter::runSession(MNN::Session*) const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:139: error: undefined reference to 'MNN::Interpreter::runSessionWithCallBack(MNN::Session const*, std::__ndk1::function<bool (std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)> const&, std::__ndk1::function<bool (std::__ndk1::vector<MNN::Tensor*, std::__ndk1::allocator<MNN::Tensor*> > const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)> const&, bool) const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:154: error: undefined reference to 'MNN::Interpreter::resizeSession(MNN::Session*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:163: error: undefined reference to 'MNN::Interpreter::getSessionInput(MNN::Session const*, char const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:167: error: undefined reference to 'MNN::Interpreter::getSessionInput(MNN::Session const*, char const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:178: error: undefined reference to 'MNN::Interpreter::getSessionOutput(MNN::Session const*, char const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:181: error: undefined reference to 'MNN::Interpreter::getSessionOutput(MNN::Session const*, char const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:198: error: undefined reference to 'MNN::Interpreter::resizeTensor(MNN::Tensor*, std::__ndk1::vector<int, std::__ndk1::allocator<int> > const&)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:257: error: undefined reference to 'MNN::Tensor::getDimensionType() const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:257: error: undefined reference to 'MNN::Tensor::Tensor(MNN::Tensor const*, MNN::Tensor::DimensionType, bool)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:258: error: undefined reference to 'MNN::Tensor::copyToHostTensor(MNN::Tensor*) const'
../../../../includes/MNN/Tensor.hpp:226: error: undefined reference to 'MNN::Tensor::size() const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:287: error: undefined reference to 'MNN::Tensor::getDimensionType() const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:287: error: undefined reference to 'MNN::Tensor::Tensor(MNN::Tensor const*, MNN::Tensor::DimensionType, bool)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:288: error: undefined reference to 'MNN::Tensor::copyToHostTensor(MNN::Tensor*) const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:310: error: undefined reference to 'MNN::Tensor::getDimensionType() const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:310: error: undefined reference to 'MNN::Tensor::Tensor(MNN::Tensor const*, MNN::Tensor::DimensionType, bool)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:314: error: undefined reference to 'MNN::Tensor::getDimensionType() const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:314: error: undefined reference to 'MNN::Tensor::Tensor(MNN::Tensor const*, MNN::Tensor::DimensionType, bool)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:315: error: undefined reference to 'MNN::Tensor::copyToHostTensor(MNN::Tensor*) const'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:366: error: undefined reference to 'MNN::CV::Matrix::set9(float const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:369: error: undefined reference to 'MNN::CV::ImageProcess::create(MNN::CV::ImageProcess::Config const&, MNN::Tensor const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:370: error: undefined reference to 'MNN::CV::ImageProcess::setMatrix(MNN::CV::Matrix const&)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:374: error: undefined reference to 'MNN::CV::ImageProcess::convert(unsigned char const*, int, int, int, MNN::Tensor*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:422: error: undefined reference to 'MNN::CV::Matrix::set9(float const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:425: error: undefined reference to 'MNN::CV::ImageProcess::create(MNN::CV::ImageProcess::Config const&, MNN::Tensor const*)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:426: error: undefined reference to 'MNN::CV::ImageProcess::setMatrix(MNN::CV::Matrix const&)'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:432: error: undefined reference to 'MNN::CV::ImageProcess::convert(unsigned char const*, int, int, int, MNN::Tensor*)'
../../../../includes/MNN/Matrix.h:536: error: undefined reference to 'MNN::CV::Matrix::reset()'
MNN_root/demo/android/app/src/main/jni/mnnnetnative.cpp:129: error: undefined reference to 'MNN::Tensor::copyToHostTensor(MNN::Tensor*) const'
sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:2338: error: undefined reference to 'MNN::Tensor::~Tensor()'
sdk_root/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/memory:2338: error: undefined reference to 'MNN::CV::ImageProcess::~ImageProcess()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Please let me know if you managed to resolve the issue?

**Comment by yousefabohend** [comment]
I run it on windows so i cannot do that . if you have in suggests ?

**Comment by yousefabohend** [comment]
Did you try to do the steps in this link 
https://www.yuque.com/mnn/en/build_android

**Comment by yehorchankov** [comment]
In the error message that you provided, it states that your android build misses `libs/armeabi-v7a/libMNN.so` file. So you can either build it by yourself by following this instruction: https://www.yuque.com/mnn/en/build_android or you can download it from releases: https://github.com/alibaba/MNN/releases

**Comment by kunalgoyal9** [comment]
@yehorchankov Have you got clang error solved?

**Comment by yehorchankov** [comment]
@kunalgoyal9 hello! Yes, I have solved the issue. I can't say what exactly helped me, but here's what I've tried:
- Updated compiler and libs
- Tried different build options in `project/android/build_*.sh`
- Reinstalled NDK

**Comment by zbuchanancreative** [comment]
I am having similar issues building. Does anyone know of an AAR that I can import into an Android project directly. Hopefully one that contains the JNI interface to the native face detection code.
