### ISSUE TITLE
An android demo error, solved by turn off the instant run, but why can't instant run been applied?

### ISSUE THREAD

**Issue by GaussRieman** [alibaba/MNN#64]
#### Android Studio报错

```java
2019-05-13 14:38:26.816 21653-21653/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.taobao.android.mnndemo, PID: 21653
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.taobao.android.mnndemo/com.taobao.android.mnndemo.VideoActivity}: java.lang.ClassNotFoundException: Didn't find class "com.taobao.android.mnndemo.VideoActivity" on path: DexPathList[[zip file "/data/app/com.taobao.android.mnndemo-XLHXc1msoLEj8_JRUFdEiQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.android.mnndemo-XLHXc1msoLEj8_JRUFdEiQ==/lib/arm64, /data/app/com.taobao.android.mnndemo-XLHXc1msoLEj8_JRUFdEiQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2901)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:187)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.taobao.android.mnndemo.VideoActivity" on path: DexPathList[[zip file "/data/app/com.taobao.android.mnndemo-XLHXc1msoLEj8_JRUFdEiQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.taobao.android.mnndemo-XLHXc1msoLEj8_JRUFdEiQ==/lib/arm64, /data/app/com.taobao.android.mnndemo-XLHXc1msoLEj8_JRUFdEiQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2891)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3078) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:187) 
        at android.app.ActivityThread.main(ActivityThread.java:7021) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888) 
```

#### 解决办法
[迷之解决](https://stackoverflow.com/questions/22399572/java-lang-classnotfoundexception-didnt-find-class-on-path-dexpathlist) 

`` File -> Settings -> Build,Execution, Deployment -> Instant Run -> Uncheck the checkbox for instant run``

![20190513-150957](https://user-images.githubusercontent.com/20228088/57668516-2efca200-763a-11e9-90a3-4e9ad7115eb9.png)

**Comment by suancaiyu** [comment]
这个应该是安卓低版本Dex分包造成的，部署到API20以下的设备上，AS会停用Instant Run
